// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public static class MLModel
{
    public partial class CollaborativeFilteringModel
    {
        /// <summary>
        /// model input class for CollaborativeFilteringModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"userID")]
            public float UserID { get; set; }

            [ColumnName(@"itemID")]
            public float ItemID { get; set; }

            [ColumnName(@"rating")]
            public float Rating { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CollaborativeFilteringModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"userID")]
            public uint UserID { get; set; }

            [ColumnName(@"itemID")]
            public uint ItemID { get; set; }

            [ColumnName(@"rating")]
            public float Rating { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine().Result, true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static async Task<PredictionEngine<ModelInput, ModelOutput>> CreatePredictEngine()
        {
            const string MLNetModelPath = "CollaborativeFilteringModel.zip";
            using var stream = await FileSystem.OpenAppPackageFileAsync(MLNetModelPath);
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(stream, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
